---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebo
  labels:
    app.kubernetes.io/name: ebo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: ebo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ebo
    spec:
      serviceAccountName: ebo
      securityContext:
        {}
      containers:
        - name: ebo
          envFrom:
          - secretRef:
              name: user-login-details
          securityContext:
            {}
          image: "bitnami/apache:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
