---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-process
  labels:
    app.kubernetes.io/name: business-process
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: business-process
  template:
    metadata:
      labels:
        app.kubernetes.io/name: business-process
    spec:
      securityContext:
        {}
      containers:
        - name: business-process
          envFrom:
          - secretRef:
              name: user-login-details
          securityContext:
            {}
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi