apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-poc
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlay/poc/sealed-secret
    repoURL: https://github.com/rsarkar29/bitnami-labs-sealed-secrets-poc.git
    targetRevision: master
  syncPolicy:
    automated: {}